apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeguard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeguard
  template:
    metadata:
      labels:
        app: kubeguard
    spec:
      containers:
        - name: kubeguard-container
          image: kubeguard-scanner:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000